In [85]:
'''
This table will store the meta information about each plant
'''
import sqlite3
sql_create_field_book = '''CREATE TABLE IF NOT EXISTS field_book (

plant_name text PRIMARY KEY NOT NULL UNIQUE,
treatment text NOT NULL,
plot text NOT NULL,
genotype text NOT NULL,
season integer DEFAULT 10,
species text DEFAULT "lettuce"
);
'''

In [86]:
con = sqlite3.connect('po5.db')
cursor = con.cursor()
cursor.execute(sql_create_field_book)

In [10]:
import pandas as pd
from IPython.display import display
'''
I nee to collect info from other tables about treatments and plots
I will use rgb to get this info
rgb[plant_name]'''
rgb = pd.read_sql_query("SELECT * FROM rgb", con)
display(rgb)

,level_0,index,date,plant_name,treatment,plot,genotype,lon,lat,min_x,...,min_y,max_y,nw_lat,nw_lon,se_lat,se_lon,bounding_area_m2,double_plant,partial_scan,flags
0,0,0,2019-12-10,Green_Thunder_72,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076240,603.0,...,6884.0,7030.0,33.076240,-111.974954,33.076241,-111.974953,0.002087,0.0,0,"['no_dp', 'no_ps']"
1,1,1,2019-12-10,Green_Thunder_179,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076231,557.0,...,10105.0,10314.0,33.076231,-111.974954,33.076232,-111.974954,0.003463,0.0,0,"['no_dp', 'no_ps']"
2,2,2,2019-12-10,Green_Thunder_26,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076233,556.0,...,9688.0,9813.0,33.076232,-111.974954,33.076233,-111.974954,0.002063,0.0,0,"['no_dp', 'no_ps']"
3,3,3,2019-12-10,Green_Thunder_27,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974953,33.076257,670.0,...,892.0,1098.0,33.076257,-111.974954,33.076258,-111.974953,0.003587,0.0,0,"['no_dp', 'no_ps']"
4,4,4,2019-12-10,Green_Thunder_111,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076234,566.0,...,9060.0,9210.0,33.076234,-111.974954,33.076235,-111.974954,0.001834,0.0,0,"['no_dp', 'no_ps']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522425,522425,522425,2020-03-03,Infantry_44,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075678,38.0,...,840.0,1673.0,33.075676,-111.975028,33.075679,-111.975025,0.062960,0.0,0,"['no_dp', 'no_ps']"
522426,522426,522426,2020-03-03,Infantry_116,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075657,24.0,...,7555.0,8466.0,33.075656,-111.975028,33.075658,-111.975025,0.064303,0.0,0,"['no_dp', 'no_ps']"
522427,522427,522427,2020-03-03,Infantry_221,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075653,25.0,...,9004.0,9634.0,33.075652,-111.975028,33.075654,-111.975025,0.045730,0.0,0,"['no_dp', 'no_ps']"
522428,522428,522428,2020-03-03,Infantry_13,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075650,0.0,...,10112.0,10901.0,33.075648,-111.975028,33.075651,-111.975025,0.062833,1.0,0,"['dp', 'no_ps']"
522429,522429,522429,2020-03-03,Infantry_125,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975027,33.075649,34.0,...,10387.0,10878.0,33.075648,-111.975028,33.075650,-111.975026,0.028041,0.0,0,"['no_dp', 'no_ps']"

In [19]:
#get values 
plant_name_s = rgb['plot'].to_list()
print(f'plot: {len(plant_name_s)} Vs set(plot): {len(set(plant_name_s))}')
if(len(plant_name_s) > len(set(plant_name_s))):
    print(f'we have duplicates')
'''
I have a question about the structure of the database field_book
The plant_name isn't unique in rgb, meaning each plant_name has multiple input in rgb
What would be the secondary key? plot?
'''

plot: 522430 Vs set(plot): 2339
we have duplicates

In [ ]:
plant_name_s = rgb['plant_name'].to_list()
print(f'plant_names_s: {len(plant_name_s)} Vs set(plant_names_s): {len(set(plant_name_s))}')
if(len(plant_name_s) > len(set(plant_name_s))):
    print(f'we have duplicates')

In [88]:
def push_to_sql(plant_name, treatment, plot, genotype, season=10, species='lettuce'):
    sql = f'''INSERT INTO field_book(plant_name, treatment, plot, genotype, season, species) 
    VALUES("{plant_name}", "{treatment}", "{plot}", "{genotype}", {season}, "{species}");'''
    cur = con.cursor()
    
    cur.execute(sql, rgb)
    print("executed !")
    con.commit()
    print("commited !")

In [89]:
for i in range(len(rgb)):
    if(i == 10): break
    plant_name= rgb.loc[i, 'plant_name']
    treatment= rgb.loc[i, 'treatment']
    plot= rgb.loc[i, 'plot']
    genotype= rgb.loc[i, 'genotype']
    season=10
    species='lettuce'
    print(f"push_to_sql({plant_name}, {treatment}, {plot}, {genotype}, season=10, species='lettuce')")
    push_to_sql(plant_name, treatment, plot, genotype, season, species)

push_to_sql(Green_Thunder_72, treatment 3, MAC_Field_Scanner_Season_10_Range_48_Column_19, Green_Thunder, season=10, species='lettuce')

ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 522430 supplied.

In [90]:
cols = ['plant_name', 'treatment', 'plot', 'genotype']
rgb[cols].to_sql('field_book', con, if_exists='append')

522430

In [60]:
display(rgb[cols].values)

array([['Green_Thunder_72', 'treatment 3',
        'MAC_Field_Scanner_Season_10_Range_48_Column_19',
        'Green_Thunder'],
       ['Green_Thunder_179', 'treatment 3',
        'MAC_Field_Scanner_Season_10_Range_48_Column_19',
        'Green_Thunder'],
       ['Green_Thunder_26', 'treatment 3',
        'MAC_Field_Scanner_Season_10_Range_48_Column_19',
        'Green_Thunder'],
       ...,
       ['Infantry_221', 'treatment 2',
        'MAC_Field_Scanner_Season_10_Range_32_Column_6', 'Infantry'],
       ['Infantry_13', 'treatment 2',
        'MAC_Field_Scanner_Season_10_Range_32_Column_6', 'Infantry'],
       ['Infantry_125', 'treatment 2',
        'MAC_Field_Scanner_Season_10_Range_32_Column_6', 'Infantry']],
      dtype=object)

In [92]:
import os
def push_to_cyverse(path, destination):
    
    command = f'''
    # add iCommands Path
    export PATH="/Applications/icommands/:$PATH"
    export IRODS_PLUGINS_HOME=/Applications/icommands/plugins/
    source ~/.zshrc
    iget -T -v {path} {destination}
    '''
    print(f'iget -T -v {path} {destination}')
    print(os.system(command))
push_to_cyverse('po5.db', '/iplant/home/travis_simmons/po_database/')

iget -T -v po5.db /iplant/home/travis_simmons/po_database/

ERROR: resolveRodsTarget: srcPath /iplant/home/hassantiger11/po5.db does not exist
ERROR: getUtil: resolveRodsTarget status = -317000 USER_INPUT_PATH_ERR

768