In [4]:
import pandas as pd
from IPython.display import display

psii_complete = pd.read_csv('season10_lettuce_complete_data.csv')
display(psii_complete)

/var/folders/5f/szscxzj17yb1j0mt6dzhwb1w0000ks/T/ipykernel_3508/1051644389.py:4: DtypeWarning: Columns (0,1,3,7,8,9,12,69,70) have mixed types. Specify dtype option on import or set low_memory=False.
  psii_complete = pd.read_csv('season10_lettuce_complete_data.csv')

,genotype,Type of Lettuce,Lettuce type,Colour,plot,date,year,experiment,field,rep,...,Range,Column,# of Heads,Plot Weight (kg),Weight per Head (kg),Unnamed: 9,height,width,length,derived_volume
0,Aido,NaN,Butterhead,NaN,541.0,2019-12-10,2019.0,lettuce_season_1,south,rep1,...,5.0,41.0,6.0,1.5,0.25,250.0,NaN,NaN,NaN,NaN
1,Aido,NaN,Butterhead,NaN,541.0,2019-12-10,2019.0,lettuce_season_1,south,rep1,...,5.0,41.0,6.0,1.5,0.25,250.0,NaN,NaN,NaN,NaN
2,Aido,NaN,Butterhead,NaN,541.0,2019-12-10,2019.0,lettuce_season_1,south,rep1,...,5.0,41.0,6.0,1.5,0.25,250.0,NaN,NaN,NaN,NaN
3,Aido,NaN,Butterhead,NaN,541.0,2019-12-10,2019.0,lettuce_season_1,south,rep1,...,5.0,41.0,6.0,1.5,0.25,250.0,NaN,NaN,NaN,NaN
4,Aido,NaN,Butterhead,NaN,541.0,2019-12-10,2019.0,lettuce_season_1,south,rep1,...,5.0,41.0,6.0,1.5,0.25,250.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
819437,NaN,NaN,Unknown,NaN,NaN,2020-03-02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.585820,1.126989,1.212495,0.800504
819438,NaN,NaN,Unknown,NaN,NaN,2020-03-02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.558771,1.105773,1.315277,0.812676
819439,NaN,NaN,Unknown,NaN,NaN,2020-03-02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.540186,1.187324,1.062480,0.681449
819440,NaN,NaN,Unknown,NaN,NaN,2020-03-02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.610855,1.195608,1.237026,0.903454
819441,NaN,NaN,Unknown,NaN,NaN,2020-03-02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.482338,1.052398,1.262079,0.640646

In [5]:
import os
from IPython.display import display
def get_csv_files_paths_and_dates():
    curr_dir = os.getcwd()
    folder = 'fluorescence_outs'
    paths = {}
    for directory in os.listdir(folder):
        curr_path = os.path.join(folder, directory)
        
        date = directory.split('_')[0]
        for csv_file in os.listdir(curr_path):
            curr_path = os.path.join(curr_path, csv_file)
            paths[date] = curr_path
    print (paths)        
    return paths

In [6]:
dates =  get_csv_files_paths_and_dates()
dataframes = []
for date in dates:
    dataframes.append(psii_complete.loc[psii_complete['date'] == date])

{'2020-01-24': 'fluorescence_outs/2020-01-24_fluorescence_aggregation/2020-01-24_fluorescence_aggregation.csv', '2020-02-07': 'fluorescence_outs/2020-02-07_fluorescence_aggregation/2020-02-07_fluorescence_aggregation.csv', '2020-02-26': 'fluorescence_outs/2020-02-26_fluorescence_aggregation/2020-02-26_fluorescence_aggregation.csv', '2020-02-19': 'fluorescence_outs/2020-02-19_fluorescence_aggregation/2020-02-19_fluorescence_aggregation.csv', '2020-02-27': 'fluorescence_outs/2020-02-27_fluorescence_aggregation/2020-02-27_fluorescence_aggregation.csv', '2020-02-14': 'fluorescence_outs/2020-02-14_fluorescence_aggregation/2020-02-14_fluorescence_aggregation.csv', '2020-02-12': 'fluorescence_outs/2020-02-12_fluorescence_aggregation/2020-02-12_fluorescence_aggregation.csv', '2020-01-23': 'fluorescence_outs/2020-01-23_fluorescence_aggregation/2020-01-23_fluorescence_aggregation.csv', '2020-01-22': 'fluorescence_outs/2020-01-22_fluorescence_aggregation/2020-01-22_fluorescence_aggregation.csv', '2020-02-05': 'fluorescence_outs/2020-02-05_fluorescence_aggregation/2020-02-05_fluorescence_aggregation.csv', '2020-02-13': 'fluorescence_outs/2020-02-13_fluorescence_aggregation/2020-02-13_fluorescence_aggregation.csv', '2020-02-20': 'fluorescence_outs/2020-02-20_fluorescence_aggregation/2020-02-20_fluorescence_aggregation.csv'}

In [7]:
combined = pd.concat(dataframes, ignore_index=True)
combined.to_csv('combined.csv')
display(combined)

,genotype,Type of Lettuce,Lettuce type,Colour,plot,date,year,experiment,field,rep,...,Range,Column,# of Heads,Plot Weight (kg),Weight per Head (kg),Unnamed: 9,height,width,length,derived_volume
0,Aido,NaN,Butterhead,NaN,3839.0,2020-01-24,2019.0,lettuce_season_1,south,rep1,...,38.0,39.0,12.0,1.95,0.162500,162.500000,NaN,NaN,NaN,NaN
1,Aido,NaN,Butterhead,NaN,4328.0,2020-01-24,2019.0,lettuce_season_1,south,rep2,...,43.0,28.0,5.0,1.30,0.260000,260.000000,NaN,NaN,NaN,NaN
2,Aido,NaN,Butterhead,NaN,5214.0,2020-01-24,2019.0,lettuce_season_1,south,rep3,...,52.0,14.0,7.0,1.55,0.221429,221.428571,NaN,NaN,NaN,NaN
3,Alanis,NaN,Butterhead,NaN,3918.0,2020-01-24,2019.0,lettuce_season_1,south,rep1,...,39.0,18.0,5.0,1.65,0.330000,330.000000,NaN,NaN,NaN,NaN
4,Alanis,NaN,Butterhead,NaN,4623.0,2020-01-24,2019.0,lettuce_season_1,south,rep2,...,46.0,23.0,6.0,2.25,0.375000,375.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70929,Xanadu,Romaine,Romaine mini,Green,5039.0,2020-02-20,2019.0,lettuce_season_1,south,rep3,...,50.0,39.0,10.0,4.10,0.410000,410.000000,NaN,NaN,NaN,NaN
70930,Xanadu,Romaine,Romaine mini,Green,5039.0,2020-02-20,2019.0,lettuce_season_1,south,rep3,...,50.0,39.0,10.0,4.10,0.410000,410.000000,NaN,NaN,NaN,NaN
70931,Xanadu,Romaine,Romaine mini,Green,5039.0,2020-02-20,2019.0,lettuce_season_1,south,rep3,...,50.0,39.0,10.0,4.10,0.410000,410.000000,NaN,NaN,NaN,NaN
70932,Xanadu,Romaine,Romaine mini,Green,5039.0,2020-02-20,2019.0,lettuce_season_1,south,rep3,...,50.0,39.0,10.0,4.10,0.410000,410.000000,NaN,NaN,NaN,NaN
70933,Xanadu,Romaine,Romaine mini,Green,5039.0,2020-02-20,2019.0,lettuce_season_1,south,rep3,...,50.0,39.0,10.0,4.10,0.410000,410.000000,NaN,NaN,NaN,NaN