In [7]:
'''
All imports & global values
'''
import sqlite3
import pandas as pd
from IPython.display import display
po5 = sqlite3.connect("po5.db")

In [11]:
import sqlite3
import pandas as pd
from IPython.display import display
with sqlite3.connect('po3.db') as con:
    psii = pd.read_sql_query("SELECT * from psii;", con)
    print(f'psii: ')
    display(psii)
    
    
    rgb = pd.read_sql_query("SELECT * from rgb;", con)
    print(f'rgb: ')
    display(rgb)
    
    

    scanner3d = pd.read_sql_query("SELECT * from scanner3d;", con)
    print(f'scanner3d: ')
    display(scanner3d)
    
    flir = pd.read_sql_query("SELECT * from flir;", con)
    print(f'flir: ')
    display(flir)

psii:

,index,Plot,F0,FM,FV,FV/FM,Date
0,0,MAC Field Scanner Season 10 Range 40 Column 30,13.960748,67.295251,53.334503,0.792545,2020-01-24
1,1,MAC Field Scanner Season 10 Range 41 Column 19,13.508523,59.143537,45.635015,0.771598,2020-01-24
2,2,MAC Field Scanner Season 10 Range 49 Column 21,12.215608,35.536869,23.321261,0.656255,2020-01-24
3,3,MAC Field Scanner Season 10 Range 38 Column 45,11.659572,41.517839,29.858267,0.719167,2020-01-24
4,4,MAC Field Scanner Season 10 Range 41 Column 7,13.102145,54.621915,41.519770,0.760130,2020-01-24
...,...,...,...,...,...,...,...
8635,8635,MAC Field Scanner Season 10 Range 51 Column 40,16.205196,82.241268,66.036072,0.802955,2020-02-20
8636,8636,MAC Field Scanner Season 10 Range 38 Column 10,15.725742,89.299231,73.573489,0.823898,2020-02-20
8637,8637,MAC Field Scanner Season 10 Range 39 Column 7,15.577724,79.912716,64.334992,0.805066,2020-02-20
8638,8638,MAC Field Scanner Season 10 Range 37 Column 40,16.357797,85.199033,68.841236,0.808005,2020-02-20
8639,8639,MAC Field Scanner Season 10 Range 48 Column 34,15.355225,81.264952,65.909726,0.811047,2020-02-20

rgb:

,level_0,index,date,plant_name,treatment,plot,genotype,lon,lat,min_x,...,min_y,max_y,nw_lat,nw_lon,se_lat,se_lon,bounding_area_m2,double_plant,partial_scan,flags
0,0,0,2019-12-10,Green_Thunder_72,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076240,603.0,...,6884.0,7030.0,33.076240,-111.974954,33.076241,-111.974953,0.002087,0.0,0,"['no_dp', 'no_ps']"
1,1,1,2019-12-10,Green_Thunder_179,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076231,557.0,...,10105.0,10314.0,33.076231,-111.974954,33.076232,-111.974954,0.003463,0.0,0,"['no_dp', 'no_ps']"
2,2,2,2019-12-10,Green_Thunder_26,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076233,556.0,...,9688.0,9813.0,33.076232,-111.974954,33.076233,-111.974954,0.002063,0.0,0,"['no_dp', 'no_ps']"
3,3,3,2019-12-10,Green_Thunder_27,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974953,33.076257,670.0,...,892.0,1098.0,33.076257,-111.974954,33.076258,-111.974953,0.003587,0.0,0,"['no_dp', 'no_ps']"
4,4,4,2019-12-10,Green_Thunder_111,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076234,566.0,...,9060.0,9210.0,33.076234,-111.974954,33.076235,-111.974954,0.001834,0.0,0,"['no_dp', 'no_ps']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522425,522425,522425,2020-03-03,Infantry_44,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075678,38.0,...,840.0,1673.0,33.075676,-111.975028,33.075679,-111.975025,0.062960,0.0,0,"['no_dp', 'no_ps']"
522426,522426,522426,2020-03-03,Infantry_116,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075657,24.0,...,7555.0,8466.0,33.075656,-111.975028,33.075658,-111.975025,0.064303,0.0,0,"['no_dp', 'no_ps']"
522427,522427,522427,2020-03-03,Infantry_221,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075653,25.0,...,9004.0,9634.0,33.075652,-111.975028,33.075654,-111.975025,0.045730,0.0,0,"['no_dp', 'no_ps']"
522428,522428,522428,2020-03-03,Infantry_13,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075650,0.0,...,10112.0,10901.0,33.075648,-111.975028,33.075651,-111.975025,0.062833,1.0,0,"['dp', 'no_ps']"
522429,522429,522429,2020-03-03,Infantry_125,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975027,33.075649,34.0,...,10387.0,10878.0,33.075648,-111.975028,33.075650,-111.975026,0.028041,0.0,0,"['no_dp', 'no_ps']"

scanner3d:

,index,plant_name,min_x,min_y,min_z,max_x,max_y,max_z,num_points,hull_volume,...,amplitude_silhouette_1,amplitude_silhouette_2,amplitude_heat_0,amplitude_heat_1,amplitude_heat_2,amplitude_persistence_image_0,amplitude_persistence_image_1,amplitude_persistence_image_2,Unnamed: 0,date
0,0,Aido_100,-0.687389,-0.595167,-0.150176,0.746004,0.606181,0.422280,89348.0,0.434232,...,0.001013,0.000073,145.303819,25.233863,0.125093,680.452694,272.104394,5.423737,None,2020-02-04
1,1,Aido_123,-0.610331,-0.630662,-0.144634,0.685339,0.590249,0.388524,77074.0,0.431524,...,0.001381,0.000120,132.971104,66.151870,1.032622,666.057662,479.197713,15.301617,None,2020-02-04
2,2,Aido_124,-0.633510,-0.469131,-0.132039,0.696690,0.568071,0.371267,80770.0,0.313059,...,0.000979,0.000146,106.768368,20.405339,0.168299,531.643822,231.193092,4.792345,None,2020-02-04
3,3,Aido_170,-0.629430,-0.611257,-0.122805,0.673616,0.630074,0.410606,76509.0,0.424726,...,0.001414,0.000109,249.416043,34.213248,1.050909,853.015157,352.659495,14.834217,None,2020-02-04
4,4,Aido_17,-0.719136,-0.638537,-0.172508,0.624592,0.620152,0.449815,97346.0,0.532415,...,0.001043,0.000266,220.631958,78.159572,0.967256,910.722242,555.693687,25.633030,None,2020-02-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233424,233424,Xanadu_76,-0.597826,-0.609573,-0.252595,0.616526,0.560529,0.474439,245360.0,0.552743,...,0.001412,0.000145,181.811835,69.319188,1.177465,890.969786,517.308973,22.426362,None,2020-03-01
233425,233425,Xanadu_8,-0.630640,-0.472916,-0.215037,0.550954,0.528322,0.443267,216467.0,0.436295,...,0.001245,0.000114,199.215656,65.468589,1.415466,832.381336,564.594934,30.879220,None,2020-03-01
233426,233426,Xanadu_94,-0.626679,-0.588491,-0.283969,0.497416,0.604982,0.437504,300260.0,0.612409,...,0.001188,0.000220,182.770835,123.040565,5.970483,919.643662,806.102629,70.811392,None,2020-03-01
233427,233427,Xanadu_98,-0.576985,-0.599891,-0.236748,0.622695,0.581644,0.454444,218908.0,0.531995,...,0.001232,0.000151,294.568496,72.640614,1.997844,974.966098,570.423287,31.252020,None,2020-03-01
233428,233428,Xanadu_99,-0.693971,-0.589926,-0.213135,0.661883,0.562856,0.554196,91399.0,0.661665,...,0.001264,0.000314,267.487977,87.133856,3.239008,1049.702627,632.685261,35.598048,None,2020-03-01

flir:

,level_0,index,date,treatment,plot,genotype,lon,lat,min_x,max_x,...,roi_temp,quartile_1,mean,median,quartile_3,variance,std_dev,labels,plant_name,double_lettuce
0,0,2727,2020-02-03,border,MAC_Field_Scanner_Season_10_Range_30_Column_1,Green_Towers_BORDER,-111.975051,33.075605,47,156,...,290.417847,289.611664,290.018616,289.993835,290.434509,0.340766,0.583752,7,Green_Towers_BORDER_20,0.0
1,1,2728,2020-02-03,border,MAC_Field_Scanner_Season_10_Range_30_Column_1,Green_Towers_BORDER,-111.975051,33.075595,76,159,...,288.961121,289.463745,289.917511,289.893402,290.361206,0.438936,0.662523,5,Green_Towers_BORDER_1824,0.0
2,2,1875,2020-02-04,border,MAC_Field_Scanner_Season_10_Range_30_Column_1,Green_Towers_BORDER,-111.975051,33.075595,23,163,...,284.915924,282.705139,284.481445,283.935211,285.879272,5.080338,2.253961,5,Green_Towers_BORDER_1824,0.0
3,3,2674,2020-02-08,border,MAC_Field_Scanner_Season_10_Range_30_Column_1,Green_Towers_BORDER,-111.975051,33.075583,80,148,...,297.186127,295.671661,296.946320,296.808838,298.032288,2.890831,1.700244,6,Green_Towers_BORDER_977,0.0
4,4,1337,2020-02-12,border,MAC_Field_Scanner_Season_10_Range_30_Column_1,Green_Towers_BORDER,-111.975051,33.075586,54,124,...,293.178406,292.528870,293.533295,293.327209,294.144806,2.416527,1.554518,3,Green_Towers_BORDER_919,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200509,200509,12268,2020-03-03,border,MAC_Field_Scanner_Season_10_Range_53_Column_39,Green_Towers_BORDER,-111.974845,33.076414,36,151,...,286.531860,286.281525,286.912720,286.670624,287.457764,0.663419,0.814505,6,Green_Towers_BORDER_5513,0.0
200510,200510,12269,2020-03-03,border,MAC_Field_Scanner_Season_10_Range_53_Column_39,Green_Towers_BORDER,-111.974845,33.076423,15,163,...,285.459778,285.904785,286.586945,286.344177,287.189240,0.924720,0.961624,3,Green_Towers_BORDER_1197,0.0
200511,200511,12270,2020-03-03,border,MAC_Field_Scanner_Season_10_Range_53_Column_39,Green_Towers_BORDER,-111.974845,33.076411,40,129,...,285.575623,285.722839,285.973083,285.981659,286.211884,0.123712,0.351728,0,Green_Towers_BORDER_570,0.0
200512,200512,12271,2020-03-03,border,MAC_Field_Scanner_Season_10_Range_53_Column_39,Green_Towers_BORDER,-111.974845,33.076417,34,160,...,286.072418,286.211884,287.106049,286.733032,287.869415,1.512649,1.229898,4,Green_Towers_BORDER_1730,0.0
200513,200513,12272,2020-03-03,border,MAC_Field_Scanner_Season_10_Range_53_Column_39,Green_Towers_BORDER,-111.974845,33.076408,40,139,...,286.874939,286.413727,287.204224,286.989044,287.903625,0.827852,0.909864,7,Green_Towers_BORDER_838,0.0

rgb with teatment 3:
        level_0   index        date         plant_name    treatment  \
0             0       0  2019-12-10   Green_Thunder_72  treatment 3
1             1       1  2019-12-10  Green_Thunder_179  treatment 3
2             2       2  2019-12-10   Green_Thunder_26  treatment 3
3             3       3  2019-12-10   Green_Thunder_27  treatment 3
4             4       4  2019-12-10  Green_Thunder_111  treatment 3
...         ...     ...         ...                ...          ...
522394   522394  522394  2020-03-03        Infantry_99  treatment 3
522395   522395  522395  2020-03-03        Infantry_26  treatment 3
522396   522396  522396  2020-03-03       Infantry_119  treatment 3
522397   522397  522397  2020-03-03        Infantry_19  treatment 3
522398   522398  522398  2020-03-03        Infantry_10  treatment 3

                                                  plot       genotype  \
0       MAC_Field_Scanner_Season_10_Range_48_Column_19  Green_Thunder
1       MAC_Field_Scanner_Season_10_Range_48_Column_19  Green_Thunder
2       MAC_Field_Scanner_Season_10_Range_48_Column_19  Green_Thunder
3       MAC_Field_Scanner_Season_10_Range_48_Column_19  Green_Thunder
4       MAC_Field_Scanner_Season_10_Range_48_Column_19  Green_Thunder
...                                                ...            ...
522394  MAC_Field_Scanner_Season_10_Range_52_Column_21       Infantry
522395  MAC_Field_Scanner_Season_10_Range_52_Column_21       Infantry
522396  MAC_Field_Scanner_Season_10_Range_52_Column_21       Infantry
522397  MAC_Field_Scanner_Season_10_Range_52_Column_21       Infantry
522398  MAC_Field_Scanner_Season_10_Range_52_Column_21       Infantry

               lon        lat  min_x  ...    min_y    max_y     nw_lat  \
0      -111.974954  33.076240  603.0  ...   6884.0   7030.0  33.076240
1      -111.974954  33.076231  557.0  ...  10105.0  10314.0  33.076231
2      -111.974954  33.076233  556.0  ...   9688.0   9813.0  33.076232
3      -111.974953  33.076257  670.0  ...    892.0   1098.0  33.076257
4      -111.974954  33.076234  566.0  ...   9060.0   9210.0  33.076234
...            ...        ...    ...  ...      ...      ...        ...
522394 -111.974943  33.076393  277.0  ...   3774.0   4534.0  33.076392
522395 -111.974943  33.076396  235.0  ...   2912.0   3524.0  33.076395
522396 -111.974943  33.076385  374.0  ...   6310.0   7079.0  33.076384
522397 -111.974943  33.076383  230.0  ...   7204.0   7934.0  33.076382
522398 -111.974943  33.076373  283.0  ...  10207.0  11326.0  33.076371

            nw_lon     se_lat      se_lon  bounding_area_m2  double_plant  \
0      -111.974954  33.076241 -111.974953          0.002087           0.0
1      -111.974954  33.076232 -111.974954          0.003463           0.0
2      -111.974954  33.076233 -111.974954          0.002063           0.0
3      -111.974954  33.076258 -111.974953          0.003587           0.0
4      -111.974954  33.076235 -111.974954          0.001834           0.0
...            ...        ...         ...               ...           ...
522394 -111.974944  33.076394 -111.974941          0.069372           0.0
522395 -111.974944  33.076397 -111.974942          0.047261           0.0
522396 -111.974944  33.076387 -111.974941          0.063887           0.0
522397 -111.974944  33.076384 -111.974942          0.057902           1.0
522398 -111.974944  33.076375 -111.974941          0.094728           1.0

        partial_scan               flags
0                  0  ['no_dp', 'no_ps']
1                  0  ['no_dp', 'no_ps']
2                  0  ['no_dp', 'no_ps']
3                  0  ['no_dp', 'no_ps']
4                  0  ['no_dp', 'no_ps']
...              ...                 ...
522394             0  ['no_dp', 'no_ps']
522395             0  ['no_dp', 'no_ps']
522396             0  ['no_dp', 'no_ps']
522397             0     ['dp', 'no_ps']
522398             0     ['dp', 'no_ps']

[155752 rows x 21 columns]

In [14]:
cols = rgb.loc[lambda df: df['treatment'] == "treatment 2"]
display(cols)

,level_0,index,date,plant_name,treatment,plot,genotype,lon,lat,min_x,...,min_y,max_y,nw_lat,nw_lon,se_lat,se_lon,bounding_area_m2,double_plant,partial_scan,flags
8,8,8,2019-12-10,Green_Thunder_91,treatment 2,MAC_Field_Scanner_Season_10_Range_26_Column_33,Green_Thunder,-111.974878,33.075460,462.0,...,870.0,1069.0,33.075460,-111.974878,33.075460,-111.974878,0.004071,0.0,0,"['no_dp', 'no_ps']"
9,9,9,2019-12-10,Green_Thunder_112,treatment 2,MAC_Field_Scanner_Season_10_Range_26_Column_33,Green_Thunder,-111.974878,33.075452,497.0,...,3927.0,4107.0,33.075451,-111.974878,33.075452,-111.974878,0.002305,0.0,0,"['no_dp', 'no_ps']"
10,10,10,2019-12-10,Green_Thunder_114,treatment 2,MAC_Field_Scanner_Season_10_Range_26_Column_33,Green_Thunder,-111.974878,33.075453,492.0,...,3554.0,3672.0,33.075453,-111.974878,33.075453,-111.974878,0.001377,0.0,0,"['no_dp', 'no_ps']"
11,11,11,2019-12-10,Green_Thunder_89,treatment 2,MAC_Field_Scanner_Season_10_Range_26_Column_33,Green_Thunder,-111.974878,33.075435,478.0,...,9804.0,9987.0,33.075435,-111.974878,33.075435,-111.974878,0.002292,0.0,0,"['no_dp', 'no_ps']"
12,12,12,2019-12-10,Green_Thunder_4,treatment 2,MAC_Field_Scanner_Season_10_Range_26_Column_33,Green_Thunder,-111.974878,33.075445,495.0,...,6349.0,6476.0,33.075445,-111.974878,33.075445,-111.974878,0.001484,0.0,0,"['no_dp', 'no_ps']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522425,522425,522425,2020-03-03,Infantry_44,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075678,38.0,...,840.0,1673.0,33.075676,-111.975028,33.075679,-111.975025,0.062960,0.0,0,"['no_dp', 'no_ps']"
522426,522426,522426,2020-03-03,Infantry_116,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075657,24.0,...,7555.0,8466.0,33.075656,-111.975028,33.075658,-111.975025,0.064303,0.0,0,"['no_dp', 'no_ps']"
522427,522427,522427,2020-03-03,Infantry_221,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075653,25.0,...,9004.0,9634.0,33.075652,-111.975028,33.075654,-111.975025,0.045730,0.0,0,"['no_dp', 'no_ps']"
522428,522428,522428,2020-03-03,Infantry_13,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075650,0.0,...,10112.0,10901.0,33.075648,-111.975028,33.075651,-111.975025,0.062833,1.0,0,"['dp', 'no_ps']"
522429,522429,522429,2020-03-03,Infantry_125,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975027,33.075649,34.0,...,10387.0,10878.0,33.075648,-111.975028,33.075650,-111.975026,0.028041,0.0,0,"['no_dp', 'no_ps']"

In [8]:
'''
psii: has column index that is a replica of SQL auto id
rgb: has index & (Unamed:0 is off by 49173 values but there is only 522430 rows) that are replica of SQL auto id
scammer3d has Index that is replica of SQL auto id
flir has level_0 is replica of SQL auto id. I am not sure what index is refering to

'''
with sqlite3.connect('po3.db') as con:
    rgb = pd.read_sql_query("SELECT * from rgb;", con)
    print(f'rgb: {rgb.columns}')
    display(rgb)

rgb: Index(['index', 'Unnamed: 0', 'plant_name', 'date', 'treatment', 'plot',
       'genotype', 'lon', 'lat', 'min_x', 'max_x', 'min_y', 'max_y', 'nw_lat',
       'nw_lon', 'se_lat', 'se_lon', 'bounding_area_m2', 'double_lettuce',
       'Unnamed: 0.1', 'geometry', 'index_right', 'ID'],
      dtype='object')

,index,Unnamed: 0,plant_name,date,treatment,plot,genotype,lon,lat,min_x,...,nw_lat,nw_lon,se_lat,se_lon,bounding_area_m2,double_lettuce,Unnamed: 0.1,geometry,index_right,ID
0,0,0,Green_Thunder_72,2019-12-10,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076240,603.0,...,33.076240,-111.974954,33.076241,-111.974953,0.002087,0.0,None,None,None,None
1,1,1,Green_Thunder_179,2019-12-10,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076231,557.0,...,33.076231,-111.974954,33.076232,-111.974954,0.003463,0.0,None,None,None,None
2,2,2,Green_Thunder_26,2019-12-10,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076233,556.0,...,33.076232,-111.974954,33.076233,-111.974954,0.002063,0.0,None,None,None,None
3,3,3,Green_Thunder_27,2019-12-10,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974953,33.076257,670.0,...,33.076257,-111.974954,33.076258,-111.974953,0.003587,0.0,None,None,None,None
4,4,4,Green_Thunder_111,2019-12-10,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder,-111.974954,33.076234,566.0,...,33.076234,-111.974954,33.076235,-111.974954,0.001834,0.0,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522425,522425,571597,Infantry_44,2020-03-03,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075678,38.0,...,33.075676,-111.975028,33.075679,-111.975025,0.062960,0.0,None,None,None,None
522426,522426,571598,Infantry_116,2020-03-03,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075657,24.0,...,33.075656,-111.975028,33.075658,-111.975025,0.064303,0.0,None,None,None,None
522427,522427,571599,Infantry_221,2020-03-03,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075653,25.0,...,33.075652,-111.975028,33.075654,-111.975025,0.045730,0.0,None,None,None,None
522428,522428,571600,Infantry_13,2020-03-03,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975026,33.075650,0.0,...,33.075648,-111.975028,33.075651,-111.975025,0.062833,1.0,None,None,None,None
522429,522429,571602,Infantry_125,2020-03-03,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry,-111.975027,33.075649,34.0,...,33.075648,-111.975028,33.075650,-111.975026,0.028041,0.0,None,None,None,None

In [8]:
#all from po5 currently
field_book = pd.read_sql_query("SELECT * FROM field_book", po5)
display(field_book)
psii = pd.read_sql_query("SELECT * from psii;", po5)
rgb = pd.read_sql_query("SELECT * from rgb;", po5)
scanner3d = pd.read_sql_query("SELECT * from scanner3d;", po5)
flir = pd.read_sql_query("SELECT * from flir;", po5)

,index,plant_name,treatment,plot,genotype
0,0,Green_Thunder_72,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
1,1,Green_Thunder_179,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
2,2,Green_Thunder_26,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
3,3,Green_Thunder_27,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
4,4,Green_Thunder_111,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
...,...,...,...,...,...
57370,57370,Infantry_192,treatment 2,MAC_Field_Scanner_Season_10_Range_23_Column_32,Infantry
57371,57371,Infantry_120,treatment 1,MAC_Field_Scanner_Season_10_Range_15_Column_21,Infantry
57372,57372,Infantry_13,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry
57373,57373,Infantry_226,treatment 1,MAC_Field_Scanner_Season_10_Range_8_Column_33,Infantry
57374,57374,Infantry_269,treatment 2,MAC_Field_Scanner_Season_10_Range_23_Column_32,Infantry

In [15]:
# Understanding the tables
print(f'field_book: {field_book.columns}')

print(f'psii: {psii.columns}')

print(f'rgb: {rgb.columns}')

print(f'scanner3d: {scanner3d.columns}')

print(f'flir: {flir.columns}')

field_book: Index(['index', 'plant_name', 'treatment', 'plot', 'genotype'], dtype='object')
psii: Index(['index', 'Plot', 'F0', 'FM', 'FV', 'FV/FM', 'Date'], dtype='object')
rgb: Index(['level_0', 'index', 'date', 'plant_name', 'treatment', 'plot',
       'genotype', 'lon', 'lat', 'min_x', 'max_x', 'min_y', 'max_y', 'nw_lat',
       'nw_lon', 'se_lat', 'se_lon', 'bounding_area_m2', 'double_plant',
       'partial_scan', 'flags'],
      dtype='object')
scanner3d: Index(['index', 'plant_name', 'min_x', 'min_y', 'min_z', 'max_x', 'max_y',
       'max_z', 'num_points', 'hull_volume', 'oriented_bounding_box',
       'axis_aligned_bounding_box', 'persistence_entropy_0',
       'persistence_entropy_1', 'persistence_entropy_2', 'number_points_0',
       'number_points_1', 'number_points_2', 'amplitude_landscape_0',
       'amplitude_landscape_1', 'amplitude_landscape_2',
       'amplitude_bottleneck_0', 'amplitude_bottleneck_1',
       'amplitude_bottleneck_2', 'amplitude_wasserstein_0',
       'amplitude_wasserstein_1', 'amplitude_wasserstein_2',
       'amplitude_betti_0', 'amplitude_betti_1', 'amplitude_betti_2',
       'amplitude_silhouette_0', 'amplitude_silhouette_1',
       'amplitude_silhouette_2', 'amplitude_heat_0', 'amplitude_heat_1',
       'amplitude_heat_2', 'amplitude_persistence_image_0',
       'amplitude_persistence_image_1', 'amplitude_persistence_image_2',
       'Unnamed: 0', 'date'],
      dtype='object')
flir: Index(['level_0', 'index', 'date', 'treatment', 'plot', 'genotype', 'lon',
       'lat', 'min_x', 'max_x', 'min_y', 'max_y', 'nw_lat', 'nw_lon', 'se_lat',
       'se_lon', 'bounding_area_m2', 'roi_temp', 'quartile_1', 'mean',
       'median', 'quartile_3', 'variance', 'std_dev', 'labels', 'plant_name',
       'double_lettuce'],
      dtype='object')

In [ ]:
'''
Check for duplicates in the 
'''
#is_dups = field_book.duplicated(subset=['plant_name', 'treatment', 'plot', 'genotype'])
def check_dups(df):
    no_dups_plant_names = set(df['plant_name'])
    for name in no_dups_plant_names:
        subset_df = pd.read_sql_query(f"SELECT * FROM field_book WHERE plant_name='{name}'", po5)
        is_dups = subset_df.duplicated(duplicated(subset=['plant_name', 'treatment', 'plot', 'genotype']))
        print(is_dups.iloc[-1])
        
check_dups(field_book)

index                                                522429
plant_name                                     Infantry_125
treatment                                       treatment 2
plot          MAC_Field_Scanner_Season_10_Range_32_Column_6
genotype                                           Infantry
Name: 522429, dtype: object

In [22]:
Green_Thunder_72 = pd.read_sql_query("SELECT * FROM field_book WHERE plant_name = 'Green_Thunder_72'", po5)

In [9]:
'''
I am going to drop index
And drop all duplicates because all rows are duplicates wothout the index
'''
no_index = field_book.drop(columns='index')
display(no_index)
#clean it from dups
no_dups = no_index.drop_duplicates(keep='first', ignore_index=True)
print(f'no_dups:')
display(no_dups)

,plant_name,treatment,plot,genotype
0,Green_Thunder_72,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
1,Green_Thunder_179,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
2,Green_Thunder_26,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
3,Green_Thunder_27,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
4,Green_Thunder_111,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
...,...,...,...,...
57370,Infantry_192,treatment 2,MAC_Field_Scanner_Season_10_Range_23_Column_32,Infantry
57371,Infantry_120,treatment 1,MAC_Field_Scanner_Season_10_Range_15_Column_21,Infantry
57372,Infantry_13,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry
57373,Infantry_226,treatment 1,MAC_Field_Scanner_Season_10_Range_8_Column_33,Infantry
57374,Infantry_269,treatment 2,MAC_Field_Scanner_Season_10_Range_23_Column_32,Infantry

no_dups:

,plant_name,treatment,plot,genotype
0,Green_Thunder_72,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
1,Green_Thunder_179,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
2,Green_Thunder_26,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
3,Green_Thunder_27,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
4,Green_Thunder_111,treatment 3,MAC_Field_Scanner_Season_10_Range_48_Column_19,Green_Thunder
...,...,...,...,...
57370,Infantry_192,treatment 2,MAC_Field_Scanner_Season_10_Range_23_Column_32,Infantry
57371,Infantry_120,treatment 1,MAC_Field_Scanner_Season_10_Range_15_Column_21,Infantry
57372,Infantry_13,treatment 2,MAC_Field_Scanner_Season_10_Range_32_Column_6,Infantry
57373,Infantry_226,treatment 1,MAC_Field_Scanner_Season_10_Range_8_Column_33,Infantry
57374,Infantry_269,treatment 2,MAC_Field_Scanner_Season_10_Range_23_Column_32,Infantry

In [4]:
!cp po5.db po6.db

In [10]:
#con = po5
no_dups.to_sql('field_book', po5, if_exists='replace')

57375

In [15]:
'''
Set the primary key which is plant_name
'''
sql_command = '''

PRAGMA foreign_keys=off;

BEGIN TRANSACTION;

ALTER TABLE field_book RENAME TO old_field_book;

-- define the primary key constraint here
CREATE TABLE IF NOT EXISTS "field_book" (
  plant_name TEXT NO NULL PRIMARY KEY,
  treatment TEXT,
  plot TEXT,
  genotype TEXT
);

INSERT INTO field_book SELECT * FROM old_field_book;

DROP TABLE old_field_book;

COMMIT;

PRAGMA foreign_keys=on;


'''
cursor = po5.cursor()
cursor.executescript(sql_command)

IntegrityError: UNIQUE constraint failed: field_book.plant_name

In [ ]:
'''
This is to alter the no duplicates table and set the primary keys
'''
sql_command = '''

PRAGMA foreign_keys=off;

BEGIN TRANSACTION;

ALTER TABLE field_book RENAME TO old_field_book;

-- define the primary key constraint here
CREATE TABLE field_book ( 
plant_name TEXT NO NULL PRIMARY KEY, 
treatment TEXT NO NULL, 
plot TEXT NO NULL,
genotype TEXT NO NULL
);

INSERT INTO field_book SELECT * FROM old_field_book;

COMMIT;

PRAGMA foreign_keys=on;

'''
cursor.execute()